#!/bin/bash

idf.py -DMICROPY_BOARD=ESP32_CAM build
cd ./build;esptool.py --chip esp32 merge_bin -o firwmare_camera.bin @flash_args;cd ..
cp ./build/firwmare_camera.bin ./firmware/firwmare_camera.bin
